import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Yap Sessions",
  description: "Generated by create next app",
  icons: {
    icon: [
      { media: '(prefers-color-scheme: light)', url: '', href: '' },
      { media: '(prefers-color-scheme: dark)', url: '', href: '' },
    ]
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body>
        {children}
      </body>
    </html>
  );
}
